use_frameworks!

platform :ios, '8.0'

target 'JMSegmentedView_Example' do
  pod 'JMSegmentedView', :path => '../'

  target 'JMSegmentedView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
